name: bekjan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^3.1.0
  pinput: ^4.0.0
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.3.0
  device_info_plus: ^10.1.0
  flutter_local_notifications: ^17.1.2
#  wakelock: ^0.4.0
  connectivity_plus: ^6.0.3
  mask_text_input_formatter: ^2.9.0
  google_maps_flutter: ^2.7.0
  maps_toolkit: ^3.0.0
  location: ^6.0.2
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  flutter_pretty_dio_logger: ^3.0.0
  image_picker: ^1.1.2
  optimize_battery: ^0.0.4
  web_socket_channel: ^3.0.0
  font_awesome_flutter: ^10.7.0
  avatar_glow: ^3.0.1
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.8.0
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.0
  android_play_install_referrer: ^0.4.0
  auto_size_text: ^3.0.0
  audioplayers: ^6.0.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/i18n/
    - assets/json/
    - assets/raw/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 400
